name: CICD
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and extract binaries
        run: ./build.sh

      - name: Archive the generated binaries
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: concourse-binaries
          path: artifacts/**
